name: Code analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up composer & dependencies
      uses: addnab/docker-run-action@v3
      with:
        image: phpdockerio/php74-cli
        shell: bash
        run: |
          composer validate --strict
          composer install --prefer-dist --no-suggest

    - name: Run tests
      uses: addnab/docker-run-action@v3
      with:
        image: phpdockerio/php74-cli
        shell: bash
        run: vendor/bin/phpunit
