name: Code analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer config
      run: docker run --rm -t -v "`pwd`:/workdir" -w /workdir phpdockerio/php74-cli composer --validate --strict

    - name: Install dependencies
      run: docker run --rm -t -v "`pwd`:/workdir" -w /workdir phpdockerio/php74-cli composer install

    - name: Run tests
      run: docker run --rm -t -v "`pwd`:/workdir" -w /workdir phpdockerio/php74-cli vendor/bin/phpunit
