name: Code analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up composer & dependencies
      run: docker run -v -t "`pwd`:/workdir" -w /workdir phpdockerio/php74-cli bash -c "composer -validate --strict; composer -o install"

    - name: Run tests
      run: docker run -v -t "`pwd`:/workdir" -w /workdir phpdockerio/php74-cli vendor/bin/phpunit

#      uses: addnab/docker-run-action@v3
#
#      with:
#        image: phpdockerio/php74-cli
#        run: |
#          composer validate --strict
#          composer install
#
#    - name: Run tests
#      uses: addnab/docker-run-action@v3
#      with:
#        image: phpdockerio/php74-cli
#        run: vendor/bin/phpunit
